apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: react-6563a38c-618f-48c0-ab15-46221fdfac9f-certificate
  namespace: react-6563a38c-618f-48c0-ab15-46221fdfac9f
spec:
  secretName: react-6563a38c-618f-48c0-ab15-46221fdfac9f-secret-tls
  commonName: lyna-react.tinhlgkiddy.fun
  dnsNames:
  - lyna-react.tinhlgkiddy.fun
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
